- name: Variable from PLAY level
  hosts: localhost
  vars:
    NAME: "Prem"
    COURSE: "DevOps" 
  tasks:
    - name: Print the below 
      ansible.builtin.debug:
        msg: "Hello {{NAME}}, Good Morning. I'm learning {{COURSE}}"