- name: loops
  hosts: localhost
  become: yes   
  tasks:
    - name: Install and uninstall the multiple packages using loop
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}" 
      loop:
      - { name: 'nginx', state: 'absent' }
      - { name: 'git', state: 'present' }
      - { name: 'postfix', state: 'absent' }